title: My Logo
email: georgi.pandev.33@gmail.com
description: Hi there!
destination: docs
baseurl: "" 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Gpandev

# Build settings
plugins:
  - jekyll-feed


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
